### ISSUE TITLE
Heterogeneous Lists

### ISSUE THREAD

**Issue by z0mbie42** [bloom42/sane#1]
does the lists should be heterogeneous ?

**Comment by defnull** [comment]
Ask the other way around: Why should lists be restricted to a single type?  Is there a good reason for it?

**Comment by z0mbie42** [comment]
Allowing Heterogeneous Lists have a huge impact for statically typed language, for example: to which data structure do you parse the following list in `rust`, `c++`, `go`, `java`?
```san
lst = ["1", 42, { a = "3 }]
```

And in which situations do you need such a list ?

**Comment by defnull** [comment]
Parsers for typed languages would simply return `List<Object>`. The inner type of a list is dynamic, so the consumer would have to check the type of the elements, anyway. With the current restriction, or without. 

An object mapper that expects a `List<String>` would simply throw an error if it finds non-string elements in a list. It's not different from maps. A parser would parse `{ a = 5, b = "6" }` as `Map<String, Object>` initially, and only check for the specific type once the schema is validated.

I think it is not the job of the format, specification or parser to catch these errors. Schema validation is a separate step, and usually enforced by an object-mapper or validator.

**Comment by z0mbie42** [comment]
list are kept as they are today for v1.0 (deeply  homogeneous) because in TOML none have found an utility for heterogeneous arrays (https://github.com/toml-lang/toml/issues/553) and introducing  (shallow or deep) heterogeneous Lists is a backward compatible change, while removing heterogeneity is a breaking change.
