### ISSUE TITLE
Only use \n for newlines

### ISSUE THREAD

**Issue by z0mbie42** [bloom42/sane#10]
instead of  `\¶\n` or `\n`

**Comment by defnull** [comment]
Not allowing 'native' line endings on windows would make SAN a bad choice for any tool that also aims to support windows as a platform. There is a reason why support for both line endings is very common in editors or tooling. Checking out a text file from git automatically converts between `\n` and `\r\n` on windows, for example.

Parsers should issue a warning if line endings are inconsistent in the same file, though.

**Comment by z0mbie42** [comment]
Im not sure if it's like the tabs vs spaces fight,

But as you mention allowing both enable users to mix them, *which is really bad*.

Are you aware of a code editor on windows which does not natively support `\n` for newlines natively ?

**Comment by z0mbie42** [comment]
having support for both `\r\n` and `\n` as newline seems to create a lot of pain (https://github.com/Microsoft/vscode/issues/2957 -  https://github.com/Microsoft/vscode/issues/2957 - https://stackoverflow.com/questions/39525417/visual-studio-code-how-to-show-line-endings - https://stackoverflow.com/questions/48630322/atom-editor-convert-line-endings-to-unix - https://discuss.atom.io/t/set-default-line-endings-to-unix-on-windows-workstation/12691/2 - https://discuss.atom.io/t/newline-character-in-windows/13741/8 - https://stackoverflow.com/questions/82726/convert-dos-line-endings-to-linux-line-endings-in-vim...).

as for #1 for 1.0 we will keep the solution that can evolve in a non breaking way.

So in v1.0 newline will only be `\n` so if the pain is proven in the future, SANE will be able to evolve to support both `\n` and `\r\n` as newline in a backward compatible way.
