### ISSUE TITLE
C-style comments

### ISSUE THREAD

**Issue by jonathan-stark** [bloom42/sane#18]
Please consider allowing c-style multi-line comments with /* */

One of the most "human" things to do when working with a config file is to comment out a large block so that you can try some experimental config without committing to losing the original config.

There may also be an argument for C++ style // comments, though this is not as important as multi-line block commenting.

**Comment by z0mbie42** [comment]
Hi, Thank you for the suggestion.

One of SANE's primary goals are to keep it simple and to be easy to parse.

To achieve this goal 1 character comment (#) is superior than 2 (//).

and adding block comments add a lot of headache and edge cases like nested comments etc.. (https://www.google.com/search?q=block+comments+are+bad) which does not outweigh the benefits as any code editor (from Vim to IntelliJ) supports multiple single line comments insertion.

**Comment by z0mbie42** [comment]
Furthermore we can see a clear tendency in modern languages to avoid block comments (Rust, Go, Julia...)

**Comment by jonathan-stark** [comment]
I think your goal of "Human and parser friendly" is leaning toward the parser and away from the human here, and there are plenty of parser friendly solutions out there already.

The lack of any comments at all is the main reason I went looking and found sane rather than just going with JSON.

I also question your assertion of a "clear tendency in modern languages to avoid block comments".  The vast majority of languages listed here do support block comments:
https://en.wikipedia.org/wiki/Comparison_of_programming_languages_(syntax)#Comment_comparison

In particular, all of the ones your cited... rust, go and julia... support block comments, and all but go support nestable block comments... ( And go did think about it ... https://github.com/golang/go/issues/54 )

Rust has block comments:
https://doc.rust-lang.org/reference/comments.html

> /* BlockComment */ (nestable)
> /** BlockComment */ ("Outer" rustdoc comment)
> /*! BlockComment */ ("Inner" rustdoc comment)

Go has C-style comments:
https://golang.org/doc/effective_go.html

> Go provides C-style /* */ block comments and C++-style // line comments. Line comments are the norm; block comments appear mostly as package comments, but are useful within an expression or to disable large swaths of code.

Julia has multi-line block comments:
https://docs.julialang.org/en/v1/base/punctuation/index.html

> #= | begin multi-line comment (these are nestable)
> =# | end multi-line comment

So... in the end... sane is yours to do with as you see fit, but ... I'm not convinced that block comments are evil or that there's a clear tendency to avoid them :)

**Comment by z0mbie42** [comment]
Block comments are avoided at least in Rust and Go (https://golang.org/doc/effective_go.html#commentary  https://users.rust-lang.org/t/block-comments-supported/16791/5 or just https://github.com/rust-lang/rust/blob/master/src/libstd/ascii.rs).

One of the corollary of parsing friendliness is readability: It allows to have tooling (think tools like eslint or prettier in the JavaScript world) to improve consistency.

Block comments somehow breaks this consistency (how do you implement auto indentation with block comments ?) and as any code editor nowadays  support commenting multiple lines with a line comment in 1 click there is no reasons to introduce block comments with all their complexity.

I strongly believe that modern languages should be designed with tooling in mind and block comments go in the other direction.

For example, if you want to know how many commented lines you have in your files vs how many non commented. How do you proceed with block comments ? With line comments it's just a matter of `grep`.
