### ISSUE TITLE
should NaN and Inf be supported ?

### ISSUE THREAD

**Issue by z0mbie42** [bloom42/sane#8]
> I'm also not sure about including NaN as a valid value. It indicates an error and has very little use for a config file.

**Comment by defnull** [comment]
I never saw a valid reason to declare `NaN` or `Inf` in a config file, but `null` may be useful.

**Comment by z0mbie42** [comment]
`nan` and `inf` are kept in the way they are today but an indication is added to not recommend their usage. See https://github.com/toml-lang/toml/issues/389 for a deeper explanation (TL;DR: SANE offloads definitions of floats to IEEE754 for compatibility reasons).

OTHO `null` is used in programming languages  to either indicate an absence of something or a pointer pointing to nothing:
* It doesn't make sense to introduce pointer semantics in SANE.
* The absence of something is indicated by the absence of such thing
eg, if `null` would be allowed the 2 following expressions would have the same meaning
```sane
a = {
  b = null, # bad, not valid
  c  = 3
}

a = {
  c  = 3
}
```

**Comment by defnull** [comment]
I disagree. In the context of configuration or structured data, `null` or `None` has nothing to do with pointer semantics. Other popular languages (e.g. JSON, YAML) support null-values, and they have good reasons to do so.

In configuration, an existing key with no value is semantically different from an absent key, and this difference is used and useful in some contexts. For example:

* The value `null` may indicate that the user wants to disable a feature, while a missing key would fall back to a default value. Or, the other way around, `feature=null` would enable a feature with default settings, while a missing key would keep the feature disabled.
* If the mapping represents an update to an existing data structure (e.g. a previous state or an implicit default state), then `null` may be used to indicate that a key should be removed, while missing keys would keep the previous value.

Without `null`, one would have to reserve a valid value for this meaning (e.g. -1, NaN, an empty or pre-defined string) which is not always possible, or resort to additional keys to represent this third state. This is a problem I have already ran into with TOML.

But in the end, it's a matter of taste and no show stopper. I just wanted to point out that there are valid use-cases for `null` values in configuration files.

**Comment by z0mbie42** [comment]
I do not see a real example where a value other than `null` could be a good default for a `nullable` type.
